version: '3.3'

services:
  karer_web:
    container_name: karer_web
    build: .
    ports:
      - "9000:9000"
    command: sh -c "python manage.py runserver 0.0.0.0:9000"
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/app/

  karer_rabbit:
    container_name: karer_rabbit
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./.env
  
  karer_celery:
    container_name: karer_celery
    build: .
    command: celery -A core worker -l info
    volumes:
      - ./:/app/
    restart: always
    env_file:
      - ./.env
    depends_on:
      - karer_rabbit

  karer_celery_beat:
    container_name: karer_celery_beat
    build: .
    command: celery -A core beat -l info
    volumes:
      - ./:/app/
    restart: always
    env_file:
      - ./.env
    depends_on:
      - karer_rabbit

  karer_redis:
    container_name: karer_redis
    image: redis:alpine
