# Generated by Django 4.1 on 2023-03-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karer_web', '0003_rename_karers_user_karer'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='karer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
    ]
