# Generated by Django 4.1 on 2023-03-09 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karer_web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="kpp",
            field=models.CharField(blank=True, max_length=20, verbose_name="КПП"),
        ),
        migrations.AddField(
            model_name="organization",
            name="ogrn",
            field=models.CharField(blank=True, max_length=20, verbose_name="ОГРН"),
        ),
        migrations.AlterField(
            model_name="karer",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="bik",
            field=models.CharField(blank=True, max_length=255, verbose_name="ВИК"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="inn",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(10, "Неправильный ИНН")
                ],
                verbose_name="ИНН",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
        ),
    ]
