# Generated by Django 4.1 on 2023-03-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karer_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='karer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
        migrations.AddField(
            model_name='client',
            name='karer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
        migrations.AddField(
            model_name='driver',
            name='karer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
        migrations.AddField(
            model_name='organization',
            name='karer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='karers',
        ),
        migrations.AddField(
            model_name='user',
            name='karers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
    ]
