# Generated by Django 4.1 on 2023-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "karer_web",
            "0002_organization_kpp_organization_ogrn_alter_karer_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="karer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
