# Generated by Django 4.1 on 2023-03-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karer_web', '0002_car_karer_client_karer_driver_karer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='karers',
            new_name='karer',
        ),
    ]
