# Generated by Django 4.1 on 2023-04-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karer_web', '0003_rename_karers_user_karer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='karer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
    ]
