# Generated by Django 4.1 on 2023-04-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karer_web', '0005_carcontrol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarControl',
        ),
    ]
