# Generated by Django 4.1 on 2023-04-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karer_web', '0006_delete_carcontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='karer',
        ),
        migrations.RemoveField(
            model_name='client',
            name='karer',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='karer',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='karer',
        ),
        migrations.AddField(
            model_name='car',
            name='model_seria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=20, unique=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='karer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
    ]
