# Generated by Django 4.1 on 2023-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karer_web', '0008_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
