# Generated by Django 4.1 on 2023-04-14 07:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('karer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.karer', verbose_name='Объект')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Импорт юр. лицо',
                'verbose_name_plural': 'Импорты юр. лицо',
            },
        ),
        migrations.CreateModel(
            name='OrgImportInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(verbose_name='Потребность (кг)')),
                ('status', models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='created', max_length=255, verbose_name='Статус')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('position', models.PositiveIntegerField(null=True, verbose_name='Позиция')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.car', verbose_name='Номер машины')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.driver', verbose_name='Водитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_invite.orgimport', verbose_name='Импорт')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заявка юр. лицо',
                'verbose_name_plural': 'Заявкы юр. лицо',
                'ordering': ['position'],
            },
        ),
    ]
