# Generated by Django 4.1 on 2023-04-14 12:02

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
        ('import_invite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgimportinvite',
            name='status',
            field=models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='waiting_pay', max_length=255, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='HistoricalOrgImportInvite',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('weight', models.FloatField(verbose_name='Потребность (кг)')),
                ('status', models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='waiting_pay', max_length=255, verbose_name='Статус')),
                ('create_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('position', models.PositiveIntegerField(null=True, verbose_name='Позиция')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('car', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.car', verbose_name='Номер машины')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.driver', verbose_name='Водитель')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='import_invite.orgimport', verbose_name='Импорт')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'historical Заявка юр. лицо',
                'verbose_name_plural': 'historical Заявкы юр. лицо',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
