# Generated by Django 4.1 on 2023-03-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karer_web', '0001_initial'),
        ('import_invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgimportinvite',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.car', verbose_name='Номер машины'),
        ),
        migrations.AddField(
            model_name='orgimportinvite',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='orgimportinvite',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_invite.orgimport', verbose_name='Импорт'),
        ),
        migrations.AddField(
            model_name='orgimport',
            name='karer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='orgimport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='clientimportinvite',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.car', verbose_name='Номер машины'),
        ),
        migrations.AddField(
            model_name='clientimportinvite',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='clientimportinvite',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_invite.clientimport', verbose_name='Импорт'),
        ),
        migrations.AddField(
            model_name='clientimport',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.client', verbose_name='Физ. лицо'),
        ),
        migrations.AddField(
            model_name='clientimport',
            name='karer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer', verbose_name='Объект'),
        ),
    ]
