# Generated by Django 4.1 on 2023-04-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_invite', '0003_remove_clientimportinvite_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientimportinvite',
            name='car',
        ),
        migrations.RemoveField(
            model_name='clientimportinvite',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='clientimportinvite',
            name='order',
        ),
        migrations.RemoveField(
            model_name='clientimportinvite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orgimport',
            name='status',
        ),
        migrations.AlterField(
            model_name='orgimportinvite',
            name='status',
            field=models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='created', max_length=255, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='ClientImport',
        ),
        migrations.DeleteModel(
            name='ClientImportInvite',
        ),
    ]
