# Generated by Django 4.1 on 2023-04-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('car_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcontrol',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car', to_field='number', verbose_name='Машина'),
        ),
    ]
