# Generated by Django 4.1 on 2023-04-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('car_control', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarControl',
            new_name='History',
        ),
    ]
