# Generated by Django 4.1 on 2023-04-14 07:45

import uuid

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client', verbose_name='Физ. лицо')),
                ('karer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.karer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ физ. лицо',
                'verbose_name_plural': 'Заказы физ. лицо',
            },
        ),
        migrations.CreateModel(
            name='OrgOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('karer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.karer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ юр. лицо',
                'verbose_name_plural': 'Заказы юр. лицо',
            },
        ),
        migrations.CreateModel(
            name='OrgInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потребность (кг)')),
                ('status', models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='waiting_pay', max_length=255, verbose_name='Статус')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('position', models.PositiveIntegerField(null=True, verbose_name='Позиция')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.car', verbose_name='Номер машины')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.driver', verbose_name='Водитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite.orgorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заявка юр. лицо',
                'verbose_name_plural': 'Заявкы юр. лицо',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrgInvite',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потребность (кг)')),
                ('status', models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='waiting_pay', max_length=255, verbose_name='Статус')),
                ('create_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('position', models.PositiveIntegerField(null=True, verbose_name='Позиция')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('car', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.car', verbose_name='Номер машины')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.driver', verbose_name='Водитель')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invite.orgorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'historical Заявка юр. лицо',
                'verbose_name_plural': 'historical Заявкы юр. лицо',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClientInvite',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потребность (кг)')),
                ('status', models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='waiting_pay', max_length=255, verbose_name='Статус')),
                ('create_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('position', models.PositiveIntegerField(null=True, verbose_name='Позиция')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('car', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.car', verbose_name='Номер машины')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.driver', verbose_name='Водитель')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invite.clientorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'historical Заявка физ. лицо',
                'verbose_name_plural': 'historical Заявкы физ. лицо',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClientInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потребность (кг)')),
                ('status', models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='waiting_pay', max_length=255, verbose_name='Статус')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('position', models.PositiveIntegerField(null=True, verbose_name='Позиция')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.car', verbose_name='Номер машины')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.driver', verbose_name='Водитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite.clientorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заявка физ. лицо',
                'verbose_name_plural': 'Заявкы физ. лицо',
                'ordering': ['position'],
            },
        ),
    ]
