# Generated by Django 4.1 on 2023-03-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karer_web', '0001_initial'),
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgorder',
            name='karer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
        migrations.AddField(
            model_name='orgorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='orginvite',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.car', verbose_name='Номер машины'),
        ),
        migrations.AddField(
            model_name='orginvite',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='orginvite',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite.orgorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.client', verbose_name='Физ. лицо'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='karer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.karer'),
        ),
        migrations.AddField(
            model_name='clientinvite',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.car', verbose_name='Номер машины'),
        ),
        migrations.AddField(
            model_name='clientinvite',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karer_web.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='clientinvite',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite.clientorder', verbose_name='Заказ'),
        ),
    ]
