# Generated by Django 4.1 on 2023-03-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('invite', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinvite',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orginvite',
            name='name',
        ),
        migrations.AddField(
            model_name='clientinvite',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='orginvite',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.product', verbose_name='Продукт'),
        ),
    ]
