# Generated by Django 4.1 on 2023-03-28 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_remove_clientinvite_name_remove_orginvite_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvite',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потребность (кг)'),
        ),
        migrations.AlterField(
            model_name='orginvite',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Потребность (кг)'),
        ),
    ]
