# Generated by Django 4.1.1 on 2023-03-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_alter_invite_options_invite_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
