# Generated by Django 4.1 on 2023-04-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_alter_clientinvite_weight_alter_orginvite_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orgorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='clientinvite',
            name='status',
            field=models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='waiting_pay', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orginvite',
            name='status',
            field=models.CharField(choices=[('waiting_pay', 'Ожидает оплаты'), ('payed', 'Оплачено'), ('finished', 'Успешно'), ('canceled', 'Отклонена')], default='waiting_pay', max_length=255, verbose_name='Статус'),
        ),
    ]
